// <auto-generated />
using System;
using LocalDeportivo.API.LocalDeportivoDbContextFolder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LocalDeportivo.API.Migrations
{
    [DbContext(typeof(LocalDeportivoDbContext))]
    partial class LocalDeportivoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LocalDeportivo.API.Models.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdBodega")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoBodega")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCategoria")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreCategoria")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCliente")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdDetalle")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoDetalleFactura")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("Factura")
                        .HasColumnType("integer");

                    b.Property<int?>("FacturaIdId")
                        .HasColumnType("integer");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacturaIdId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleFacturas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdPersona")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CodigoEmpleado")
                        .HasColumnType("integer");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("EdadEmpleado")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoBodegaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoBodegaId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.EntradaSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdEntradaSalid")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BodegaId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoEntradaSalida")
                        .HasColumnType("integer");

                    b.Property<bool>("Entrada")
                        .HasColumnType("boolean");

                    b.Property<int?>("EntradaSalidaEmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntradaSalidaProductoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntradaSalidaSedeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("InventarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("Salida")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("EntradaSalidaEmpleadoId");

                    b.HasIndex("EntradaSalidaProductoId");

                    b.HasIndex("EntradaSalidaSedeId");

                    b.HasIndex("InventarioId");

                    b.ToTable("EntradaSalidas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdFactura")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Clienteid")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("text");

                    b.Property<int>("CodigoFactura")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdInventario")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoInventario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoProducto")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("text");

                    b.Property<int>("Precio")
                        .HasColumnType("integer");

                    b.Property<string>("ProveedorCodigoProveedor")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .HasColumnType("text");

                    b.Property<int?>("TipoProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorCodigoProveedor");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Proveedor", b =>
                {
                    b.Property<string>("CodigoProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("IdProveedor");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("NombreProveedor")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("CodigoProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdSede")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoSede")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("NombreSede")
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefonico")
                        .HasColumnType("text");

                    b.Property<int?>("SedeBodegaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SedeBodegaId");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.DetalleFactura", b =>
                {
                    b.HasOne("LocalDeportivo.API.Models.Factura", "FacturaId")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("FacturaIdId");

                    b.HasOne("LocalDeportivo.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("FacturaId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Empleado", b =>
                {
                    b.HasOne("LocalDeportivo.API.Models.Bodega", "EmpleadoBodega")
                        .WithMany("Empleados")
                        .HasForeignKey("EmpleadoBodegaId");

                    b.Navigation("EmpleadoBodega");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.EntradaSalida", b =>
                {
                    b.HasOne("LocalDeportivo.API.Models.Bodega", null)
                        .WithMany("EntradaSalidas")
                        .HasForeignKey("BodegaId");

                    b.HasOne("LocalDeportivo.API.Models.Empleado", "EntradaSalidaEmpleado")
                        .WithMany()
                        .HasForeignKey("EntradaSalidaEmpleadoId");

                    b.HasOne("LocalDeportivo.API.Models.Producto", "EntradaSalidaProducto")
                        .WithMany()
                        .HasForeignKey("EntradaSalidaProductoId");

                    b.HasOne("LocalDeportivo.API.Models.Sede", "EntradaSalidaSede")
                        .WithMany()
                        .HasForeignKey("EntradaSalidaSedeId");

                    b.HasOne("LocalDeportivo.API.Models.Inventario", null)
                        .WithMany("EntradaSalidas")
                        .HasForeignKey("InventarioId");

                    b.Navigation("EntradaSalidaEmpleado");

                    b.Navigation("EntradaSalidaProducto");

                    b.Navigation("EntradaSalidaSede");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Factura", b =>
                {
                    b.HasOne("LocalDeportivo.API.Models.Cliente", null)
                        .WithMany("Facturas")
                        .HasForeignKey("Clienteid");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Producto", b =>
                {
                    b.HasOne("LocalDeportivo.API.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorCodigoProveedor");

                    b.HasOne("LocalDeportivo.API.Models.Categoria", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("TipoProductoId");

                    b.Navigation("Proveedor");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Sede", b =>
                {
                    b.HasOne("LocalDeportivo.API.Models.Bodega", "SedeBodega")
                        .WithMany()
                        .HasForeignKey("SedeBodegaId");

                    b.Navigation("SedeBodega");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Bodega", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("EntradaSalidas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Inventario", b =>
                {
                    b.Navigation("EntradaSalidas");
                });

            modelBuilder.Entity("LocalDeportivo.API.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
